### ISSUE TITLE
Pages as plugin

### ISSUE THREAD

**Issue by teodoriu** [sgsoft-studio/base#1]
Why not make the pages module as a plugin, just like the blog?

**Comment by duysolo** [comment]
Yes, I'm thinking about that. I made it as base because I think every sites use it.

**Comment by teodoriu** [comment]
Yes, but the slug route i think is a problem.

**Comment by duysolo** [comment]
Could you explain that?
By now, the route is **domain**/slug
Blog: **domain**/slug.html

**Comment by teodoriu** [comment]
Yes, and that means that we can't have any custom routes like domain/route

**Comment by duysolo** [comment]
I know that issue. It's better if move pages into plugin.
I will do that soon.

**Comment by duysolo** [comment]
I separate the routes to config. You can modify it easily.
